name: ✅ Auto Full Video Processing

on:
  workflow_dispatch:
    inputs:
      folder_url:
        description: 'Link folder Google Drive chứa audio.zip và content.txt'
        required: true
      whisper_model:
        description: 'Model Whisper (tiny, small, medium, large)'
        required: true
        default: 'small'
      video_number:
        description: 'Số Thứ tự video (1, 2, 3, ...)'
        required: true
        default: '0'
      speed:
        description: 'Tốc độ điều chỉnh audio (ví dụ: 0.8, 1.0, 1.2)'
        required: true
        default: '0.8'
      max_words_per_line:
        description: 'Số từ tối đa mỗi dòng phụ đề (ví dụ: 1, 5, 8)'
        required: true
        default: '1'
      language:
        description: 'Ngôn ngữ của file audio (en, vi, es, etc.)'
        default: 'en'
      dpi:
        description: "DPI for slide PNGs (96=480p, 128=720p, 192=1080p)"
        required: true
        default: "192"
      resolution:
        required: true
        description: "Video resolution: 480p (default), 720p, 1080p"
        default: "1080p"
      config_key:
        description: "Slide config key"
        required: true
        default: "onyxShadowingEnglish"
      upload_to_youtube:
        required: true
        description: "Upload video to YouTube?"
        default: "false"
      maxChar:
        required: true
        description: "Số ký tự tối đa mỗi slide"
        default: "200"
      minChar:
        required: true
        description: "Số ký tự tối thiểu mỗi slide"
        default: "100"
      matchThreshold:
        required: true
        description: "Tỷ lệ khớp tối thiểu (%)"
        default: "90"
jobs:
  merge_transcribe:
    uses: ./.github/workflows/merge_adjust_transcribe.yml
    with:
      folder_url: ${{ github.event.inputs.folder_url }}
      video_number: ${{ github.event.inputs.video_number }}
      whisper_model: ${{ github.event.inputs.whisper_model }}
      speed: ${{ github.event.inputs.speed }}
      max_words_per_line: ${{ github.event.inputs.max_words_per_line }}
      language: ${{ github.event.inputs.language }}
    secrets:
      YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
      YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}


  generate_slides_video:
    needs: merge_transcribe
    uses: ./.github/workflows/process-from-drive.yml
    with:
      folder_url: ${{ github.event.inputs.folder_url }}
      video_number: ${{ github.event.inputs.video_number }}
      dpi: ${{ github.event.inputs.dpi }}
      resolution: ${{ github.event.inputs.resolution }}
      config_key: ${{ github.event.inputs.config_key }}
      upload_to_youtube: ${{ github.event.inputs.upload_to_youtube }}
      maxChar: ${{ github.event.inputs.maxChar }}
      minChar: ${{ github.event.inputs.minChar }}
      matchThreshold: ${{ github.event.inputs.matchThreshold }}
      maxOffset: ${{ github.event.inputs.maxOffset }}
    secrets:
      YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
      YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  
